server:
  port: 80
spring:
  application:
    name: service-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
    fetch-registry: true #去注册中心获取其他服务的地址
    registry-fetch-interval-seconds: 5 #间隔5S去拉取服务注册信息



